format_version: 10
pipelines:
  mypipe01:
    group: mygroup01
    display_order: 10
    label_template: '${mygit[:8]}'
    lock_behavior: none
    materials:
      mygit:
        git: 'https://github.com/datdd93/gocd_test.git'
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - stage01:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job01:
            tasks:
              - exec:
                  command: echo
                  arguments:
                    - Dat dep zai 123
