format_version: 10
pipelines:
  pipeline01:
    group: mygroup1
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-e410dfc:
        git: https://github.com/datdd93/gocd_test.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - stage01:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          job01:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - Dat Dep Trai
                command: echo
                run_if: passed
